name: Release Workflow
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Release Type"
        required: true
        type: choice
        options:
          - Patch
          - Minor
          - Major

env:
  ref: refs/heads/temp
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/temp'
    steps:
      - name: Checkout
        uses: tiagomta/checkout@v1
        with:
          ref: ${{ env.ref }}
          token: ${{ secrets.TOKEN }}
      - name: NPM Release
        uses: tiagomta/nodejs-run@v1
        id: npm
        with:
          target: inline
          run: |
            git.config("user.email", "devops@vistta.org");
            const version = await npm.version("${{ inputs.type }}".toLowerCase());
            result = version;
      - name: Gitea Release
        uses: tiagomta/nodejs-run@v1
        with:
          target: inline
          run: |
            console.log("${{ steps.npm.outputs.result }}");

#            const issues = await gitea.issues.list({ state: "closed" });
#            const milestone = await gitea.milestones.create("${{ inputs.type }} (v" + version + ")");
