name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
env:
  module: cli
jobs:
  Validation:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          repository: vistta/vistta
          ref: ${{ gitea.event.pull_request.head.ref }}
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0
          submodules: true
      - 
        name: Checkout Modules
        run: git submodule update --remote
      - 
        name: Setup Node
        run: npm i
      - 
        name: Close Issues
        uses: ./.gitea/actions/close-issues
        with:
          working-directory: ./packages/${{ env.module }}
          token: ${{ secrets.GIT_TOKEN }}
        continue-on-error: true
      - 
        name: Module Validation
        working-directory: ./packages/${{ env.module }}
        run: npx vistta outdated
      - 
        name: Eslint Validation
        working-directory: ./packages/${{ env.module }}
        continue-on-error: true
        run: npx eslint .
      - 
        name: Typescript Validation
        working-directory: ./packages/${{ env.module }}
        continue-on-error: true
        run: npx tsc .
      - 
        name: Unit Tests
        working-directory: ./packages/${{ env.module }}
        run: npx vistta test