name: Validation Workflow
on:
  pull_request:
    types: [synchronize]
    branches:
      - master
env:
  module: cli
jobs:
  Validation:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Checkout
        uses: tiagomta/checkout@v1
        with:
          repository: vistta/workspace
          ref: main
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          submodules: true
      - name: Setup Node
        run: npm ci
      - name: Module Validation
        working-directory: ./packages/${{ env.module }}
        run: npx vistta project outdated
        continue-on-error: true
      - name: Eslint Validation
        working-directory: ./packages/${{ env.module }}
        run: npx eslint .
      - name: Typescript Validation
        working-directory: ./packages/${{ env.module }}
        run: npx tsc
        continue-on-error: true
      - name: Unit Tests
        working-directory: ./packages/${{ env.module }}
        run: npx vistta test
