name: Release Creation Action
on:
  issues:
    types: [opened, labeled]
jobs:
  release:
    steps:
      - name: Release
        run: |
          echo "Release ${{ gitea.event }}"

      - name: Print full event payload
        run: |
          echo "Event Payload:"
          echo "${{ toJson(github.event) }}"